git:
  depth: 1
  quiet: true

language: cpp

matrix:
  include:
    - {name: "Ubuntu 14.04 Qt5", os: "linux", dist: "trusty",  compiler: "gcc", addons: {apt: {packages: "qtbase5-dev"}}}
    - {name: "Ubuntu 16.04 Qt5", os: "linux", dist: "xenial",  compiler: "gcc", addons: {apt: {packages: "qtbase5-dev"}}}
    - {name: "macOS", os: "osx", addons: {homebrew: {packages: "qt5"}}}

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DCMAKE_BUILD_TYPE=Debug
      cmake --build .
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DCMAKE_BUILD_TYPE=Debug         \
            -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
      cmake --build .
    fi
